#!/usr/bin/env bash
set -euxo pipefail

help_info() {
  echo "
Usage: ${0##*/} [options]
Build a release .tar.gz for Linux.

Options:
  -h    Display this help and exit.
  "
}

while getopts 'h' flag; do
  case "${flag}" in
    h) help_info; exit 0 ;;
  esac
done

export ZED_BUNDLE=true

channel=$(<crates/zed/RELEASE_CHANNEL)
target_dir="${CARGO_TARGET_DIR:-target}"
version="$(script/get-crate-version zed)"
export RELEASE_VERSION="${version}"
commit=$(git rev-parse HEAD | cut -c 1-7)
target_triple=$(rustc --version --verbose | grep host | cut -d ' ' -f2)

script/generate-licenses

export RUSTFLAGS="-C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
cargo build --release --target "${target_triple}" --package zed --package cli --package remote_server

strip --strip-debug "${target_dir}/${target_triple}/release/zed"
strip --strip-debug "${target_dir}/${target_triple}/release/cli"
strip --strip-debug "${target_dir}/${target_triple}/release/remote_server"

suffix=$([[ "$channel" != "stable" ]] && echo "-$channel" || echo "")

temp_dir=$(mktemp -d)
zed_dir="${temp_dir}/zed$suffix.app"

mkdir -p "${zed_dir}/bin" "${zed_dir}/libexec"
cp "${target_dir}/${target_triple}/release/zed" "${zed_dir}/libexec/zed-editor"
cp "${target_dir}/${target_triple}/release/cli" "${zed_dir}/bin/zed"

find_libs() {
  ldd ${target_dir}/${target_triple}/release/zed |\
  cut -d' ' -f3 |\
  grep -vE '\<(libstdc++|libc|libgcc_s|libm|libpthread|libdl)\.so'
}

mkdir -p "${zed_dir}/lib"
rm -rf "${zed_dir}/lib/*"
cp $(find_libs) "${zed_dir}/lib"

mkdir -p "${zed_dir}/share/icons/hicolor/512x512/apps"
cp "crates/zed/resources/app-icon$suffix.png" "${zed_dir}/share/icons/hicolor/512x512/apps/zed.png"
mkdir -p "${zed_dir}/share/icons/hicolor/1024x1024/apps"
cp "crates/zed/resources/app-icon$suffix@2x.png" "${zed_dir}/share/icons/hicolor/1024x1024/apps/zed.png"

export DO_STARTUP_NOTIFY="true"
export APP_CLI="zed"
export APP_ICON="zed"
export APP_ARGS="%U"

case "$channel" in
  preview) export APP_NAME="Zed Preview" ;;
  nightly) export APP_NAME="Zed Nightly" ;;
  dev) export APP_NAME="Zed Devel" ;;
  *) export APP_NAME="Zed" ;;
esac

mkdir -p "${zed_dir}/share/applications"
envsubst < "crates/zed/resources/zed.desktop.in" > "${zed_dir}/share/applications/zed$suffix.desktop"

cp "assets/licenses.md" "${zed_dir}/licenses.md"

arch=$(uname -m)
target="linux-${arch}"
archive=$([[ "$channel" == "dev" ]] && echo "zed-${commit}-${target}.tar.gz" || echo "zed-${target}.tar.gz")

rm -rf "${archive}"
ls "${target_dir}/release" | grep -E "zed(-[a-zA-Z0-9]+)?-linux-${arch}\.tar\.gz" | xargs -d "\n" -I {} rm -f "${target_dir}/release/{}" || true
tar -czvf "${target_dir}/release/$archive" -C ${temp_dir} "zed$suffix.app"

gzip --stdout --best "${target_dir}/${target_triple}/release/remote_server" > "${target_dir}/zed-remote-server-linux-${arch}.gz"
